### PR TITLE
add FreeBSD action

### PR DESCRIPTION
**Pull request by asdfugil**
Rename "Upload Release Asset Linux" which actually uploads macOS asset to "Upload Release Asset macOS"

Co-authored-by: sunchipnacho <22717474+sunflsks@users.noreply.github.com>
Signed-off-by: Nick Chan <towinchenmi@gmail.com>

### CODE REVIEW

**Comment by asdfugil** [comment]
@CRKatri would be interested in this

Also no I am not going to cry just because @CRKatri removed some archs

**Comment by CRKatri** [comment]
The Linux binaries run under the linuxulator just fine (what I do).

**Comment by CRKatri** [comment]
Closing this since we don't have that many action minutes to make this worth it 🙂

**Comment by asdfugil** [comment]
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

> GitHub Actions usage is free for both public repositories and self-hosted runners.

**Comment by CRKatri** [comment]
Sorry storage, not minutes
 
> https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
> 
> > GitHub Actions usage is free for both public repositories and self-hosted runners.

We only get 2000 minutes and 50M, we have used up all that 50M

**Comment by asdfugil** [comment]
> Sorry storage, not minutes
> 
> > https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
> > > GitHub Actions usage is free for both public repositories and self-hosted runners.
> 
> We only get 2000 minutes and 50M, we have used up all that 50M

>  For **private** repositories, each GitHub account receives a certain amount of free minutes and storage,

**Comment by asdfugil** [comment]
(this is from https://github.com/features/actions)

Screenshot_20220419_223411

**Pull request closed without merging**
